version: '3.4'

services:
  cpa-survey-postgres:
    image: postgres:15
    restart: always
    volumes:
      - ../postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: cpa-survey
      POSTGRES_PASSWORD: 123456
      TZ: America/Sao_Paulo
    networks:
      - cpa-survey-network

  api-cpa-survey:
    container_name: api-cpa-survey
    depends_on:
      - cpa-survey-postgres
    image: dockerwebapi:latest
    build: 
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "20000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - cpa-survey-network

networks:
  cpa-survey-network:
    driver: bridge
