// <auto-generated />
using Biopark.CpaSurvey.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biopark.CpaSurvey.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Biopark.CpaSurvey.Domain.Entities.Eixos.Eixo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Eixo", (string)null);
                });

            modelBuilder.Entity("Biopark.CpaSurvey.Domain.Entities.Perguntas.Pergunta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Descricao");

                    b.Property<long>("EixoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoResposta")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EixoId");

                    b.ToTable("Pergunta", (string)null);
                });

            modelBuilder.Entity("Biopark.CpaSurvey.Domain.Entities.Perguntas.Pergunta", b =>
                {
                    b.HasOne("Biopark.CpaSurvey.Domain.Entities.Eixos.Eixo", "Eixo")
                        .WithMany("Perguntas")
                        .HasForeignKey("EixoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Eixo_Pergunta_EixoId");

                    b.Navigation("Eixo");
                });

            modelBuilder.Entity("Biopark.CpaSurvey.Domain.Entities.Eixos.Eixo", b =>
                {
                    b.Navigation("Perguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
