name: Build e teste

on:
  [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.201"

      - name: Build
        run: dotnet build CpaSurvey.sln --configuration Release

      - name: Tests
        run: dotnet test